### ISSUE TITLE
Failure to authenticate with MongoDB 3.0

### ISSUE THREAD

**Issue by robertodtg** [le-yams/netbeans-mongodb#11]
Failure to authenticate with MongoDB 3.0 to users with SCRAM, success only with MONGODB-CR.

For more informations see, http://www.mongodb.com/blog/post/improved-password-based-authentication-mongodb-30-scram-explained-part-1

Tks

**Comment by le-yams** [comment]
I created  the branch [v8.0.2](https://github.com/le-yams/netbeans-mongodb/tree/v8.0.2) with the MongoDB driver latest stable version (2.13.0). The one currently used by the plugin doesn't support MongoDB 3.0 (2.11.4). 
I won't be able to test it before next week but feel free to clone the branch and test it, I'd be glad to have your feedback :-) 

Best regards, 
Yann

**Comment by le-yams** [comment]
I published the driver update (you can update the plugin in NetBeans), it should fix the problem, tell me if it's ok.
